### ISSUE TITLE
Optical Receptor on contraption infinite power

### ISSUE THREAD

**Issue by DaPuffer** [luccaPossamai/optical#1]
If you place an optical receptor on a contraption, point an optical source to the receptor,move the contraption and stop it the receptor keeps giving out rotational power without the source.

https://github.com/luccaPossamai/optical/assets/132820752/e74bf933-49a6-4c54-9aff-a0151abbb7ef

**Comment by DaPuffer** [comment]
would also be cool if receptors worked while on a contraption.

**Comment by luccaPossamai** [comment]
Hi, how are you? Forgive me for the delay in responding to you. This bug has already been noted and fixed in the next version. Thank you very much for notifying. The receptor is currently working only when the contraption stops.
