### ISSUE TITLE
Really weird lighting(could be unfixable)

### ISSUE THREAD

**Issue by DaPuffer** [luccaPossamai/optical#10]
![image](https://github.com/luccaPossamai/optical/assets/132820752/85a21b31-89bd-4a0d-8b10-00e31030ea1f)
![image](https://github.com/luccaPossamai/optical/assets/132820752/013fecd1-af40-4179-87d9-8ffabf645cff)

**Comment by luccaPossamai** [comment]
oh my god, I hadn't seen that. Thats a common problem with render types and light levels. I'l fixed it.
