### ISSUE TITLE
Suggestion : Color Sensor

### ISSUE THREAD

**Issue by OnesAndZer0s** [luccaPossamai/optical#11]
I noticed that you have made the visible light beam change color based on stained glass. Maybe being able to detect the color of the beam with a color sensor would be fun?

**Comment by luccaPossamai** [comment]
Damn thats good, this would fit perfectly I think. Given that real light are "colorized" based on material absorption, its intensity decreases and can be measured. Already thought about adding lanterns colored and activated by beam. Luckily we can see these ideas coming in future.
