### ISSUE TITLE
Light beam renders under water

### ISSUE THREAD

**Issue by Frosticle** [luccaPossamai/optical#14]
What I mean is, the water "layer" is rendering over the light beam.

![2024-06-27_11 05 09](https://github.com/luccaPossamai/optical/assets/43837518/9f00b59d-f5b4-4388-8d63-96894596bc3c)
![2024-06-27_11 05 20](https://github.com/luccaPossamai/optical/assets/43837518/3b5f6388-b2d3-42db-9e8b-d234c9ab27ba)
![2024-06-27_11 05 30](https://github.com/luccaPossamai/optical/assets/43837518/e88af548-4335-44aa-a537-dede5cecbcfc)

**Comment by luccaPossamai** [comment]
This has to do with the render type of the beam, the beam uses the beacon beam vanilla type, that has the same problem.
