### ISSUE TITLE
Suggestion: Add a way to combine beams

### ISSUE THREAD

**Issue by SPAZ97** [luccaPossamai/optical#16]
Say for example I want to make a death ray; for it to be acceptable, I would need to be able to combine the power of multiple beams into one super-concentrated beam, as well as an additional beam in the visible light spectrum for aesthetics - what's the point of having a cool death laser weapon if it doesn't have cool flashy colors?

**Comment by luccaPossamai** [comment]
Fair enough, that idea has been thought about for a long time. Thankfully soon It will come out of the paper.

**Comment by SPAZ97** [comment]
I really hope it ends up working with aeronautics/liftoff, because laser weapons are cool and all, but _orbital_ laser weapons are _way_ cooler.
