### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by DadamaldaDad** [luccaPossamai/optical#17]
I was wondering if I can use this mod in my server's modpack, but the license is very unclear.

### **DISCLAIMER: I'm not a lawyer**

It seems like you literally copy+pasted the license for the Forge mod loader.

I recommend checking [choosealicense.com](https://choosealicense.com/)

Most mods use the [MIT license](https://choosealicense.com/licenses/mit/).

**Comment by luccaPossamai** [comment]
Ohh, you're right. I forgot about this, I think the LICENSE.txt have been pushed with the other changes. I'll update this, and of course you can add the mod to your modpack.

**Comment by DadamaldaDad** [comment]
The license on CurseForge was not updated and LICENSE.txt should be deleted.

**Comment by luccaPossamai** [comment]
Yup, I just changed
