### ISSUE TITLE
Polarizing filters' problems

### ISSUE THREAD

**Issue by CHN-YunRu** [luccaPossamai/optical#19]
Why does the Optical Source emit vertically polarized visible light through this polarizing filter? In theory, the texture of a polarizing filter that polarizes light vertically should be vertical.
![2024-08-18_19 30 07](https://github.com/user-attachments/assets/6e89169e-dd26-422e-874e-bf44525480aa)
![2024-08-18_19 30 22](https://github.com/user-attachments/assets/2c6585e5-65af-448d-8fd7-2c292cf22ee5)
Horizontal texture of polarizing filter should be used in horizontal polarizing filter.
![2024-08-18_19 44 51](https://github.com/user-attachments/assets/e17c5392-e613-4fb6-a6d6-8ee6929c0831)
![2024-08-18_19 44 53](https://github.com/user-attachments/assets/6c02fb26-65c3-425f-bee5-d337ef8d9913)
And here, why is it displayed as "Negative Diagonal" ?
Hope u can solve my problems. Forgive me for not good at eng.

**Comment by luccaPossamai** [comment]
About the first question, in high school I was taught that horizontal polarization polarizes light horizontally, but that came to be a misunderstanding. You see physically, light have electric field associated in random directions(random pol.) when the light passes by a (horizontally texture)polarizing filter, the field excites the eletrons in the filter causing the horizontal component of the light to be absorbed. That way, the only components left of the electric field in the beam is exactly that one perpendicular to the direction of the strips in the texture. That way, horizontal strips polarizes vertically, vertical strips polarizes horizontal etc. I mean, thats only a simplified explanation, thats a lot more going on.

**Comment by luccaPossamai** [comment]
That case is for polarization by absorption.

**Comment by luccaPossamai** [comment]
The second one is a little confusing. You see, vertical and horizontal stripes always polarizes the same if the beam incides in the both faces of the block. That don't happen to diagonal polarization, when you turn them around you are changing the axis of the stripes. With the previous explanation, you are changing the polarization as well. If you notice, you can set the filter to be in diagonal but using the goggles the polarization depends of the face of the block you're looking at

**Comment by luccaPossamai** [comment]
Negative and Positive is really just an arbitrary choice of reference. To be more especific, you can see the negative diagonal as (-45°) and positive as (+45°) in reference to the vertical axis if the block.

**Comment by CHN-YunRu** [comment]
Yes, I used to learned about polarized light in high school and these knowledge can indeed be misleading. I learned the working principle of a polarizing filter in reality from the video yesterday.
What I want to say about the second point is "Horizontal light←→"can pass vertical strips texture, so why "positive diagonal light" can pass these strips. These stripes have the same direction as "positive diagonal light". This is different from what was mentioned above(vertical and horizontal).

**Comment by CHN-YunRu** [comment]
The light emitted by the machine is positive diagonal↙↗, the texture of negative diagonal polarizing filter is ↙↗, they are not perpendicular to each other. It is diffrenet with vertical and horizontal.  Horizontal light←→ can pass through the polarizing filter which stats are "horizontal←→", so why "Positive diagonal light↙↗" can pass through "Negative diagonal ↖↘" filter but not “Positive diagonal ↙↗".

**Comment by CHN-YunRu** [comment]
Perhaps communicating through pictures would be simpler, forgive me for not good at eng.
![890c44986923a24cc9f18a567b47f61](https://github.com/user-attachments/assets/a091f9fb-c57a-4768-8caa-1b0181c57c05)
![388ef29e5601589ed02fa12b01f6c86](https://github.com/user-attachments/assets/0f34ed0b-9527-4b27-a5bb-cf31f5da8ec4)

![72837d4cca92c3cbe0ace68615857b2](https://github.com/user-attachments/assets/c58214ac-9490-4363-a678-a336fa887e69)
![126450e6573ecdca44d3c0237251e10](https://github.com/user-attachments/assets/dfa14303-0c14-49a8-b4d3-3280ef7a1080)

**Comment by luccaPossamai** [comment]
Yes, the beam is supposed to pass. That's not intended. Maybe there's some inverted condition in the code. I'll fixed it. Thank you very much

**Comment by luccaPossamai** [comment]
Sometimes theses things related to fix bugs and think about new ideas can be a little to much. That way, I really encourage people who know I little about coding and whats happening and how to fix bugs to try out and send a pull request.

**Comment by CHN-YunRu** [comment]
Thank you very much for ur answer, this is a very creative mod. Hope you can successfully create more interesting content in the future.

**Comment by CHN-YunRu** [comment]
by the way, can i translate "optical" into "electromagnetic waves"? because except light, there are also microwaves ,radio waves and gamma ray.

**Comment by luccaPossamai** [comment]
Visible light is one thing, The absence of the word "light" in the other names makes us think that they're not light. But they are.

**Comment by CHN-YunRu** [comment]
thanks, I am trying to localize this mod,
