### ISSUE TITLE
Optical source and sensor unable to be placed on sides of blocks

### ISSUE THREAD

**Issue by DaPuffer** [luccaPossamai/optical#2]
You cannot place an optical source and sensor blocks on sides and below a block,unless there would be a solid block below it
There also should probably be side versions of the optical sensor

**Comment by luccaPossamai** [comment]
The idea of having the source attached to "suspension" blocks It's not necessary, but creating a side version I think it takes a bit of this ​​"optics laboratory" vibe. Also, creating a side version for sensor only would work if the block attached to it be energized when activated, and that remove the mechanic of intensity of beam and intensity of redstone signal. At the end, maybe a directional sensor it's a really good idea.
