### ISSUE TITLE
Chinese (Simplified) Translation for 0.2.0

### ISSUE THREAD

**Issue by CHN-YunRu** [luccaPossamai/optical#24]
[zh_cn.json](https://github.com/user-attachments/files/17084695/zh_cn.json)

And the problem which about olarizing filters I submitted earlier is still not fixed. More importantly, the source's animation disappeared.

**Comment by luccaPossamai** [comment]
Thank you very much, I'll commit the translation. Yeah, I saw that too. Just remember that I forgot to fix it.

**Comment by luccaPossamai** [comment]
Just realesed a fixed version for the bug
