### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Rodrigo816** [luccaPossamai/optical#25]
As soon as rotational force is applied (16 rpm) the server crashes immediately.

Crash Report
[crash-2024-09-22_13.19.24-server.txt](https://github.com/user-attachments/files/17095639/crash-2024-09-22_13.19.24-server.txt)

Its using the new version of create: 	create-1.20.1-0.5.1.h

**Comment by luccaPossamai** [comment]
The mod was built with create 1.20.1-0.5.1.f, the server side should work in this version but dunno about newer ones. I'll try to replicate, if you can give me more information about how did you did it. Wich component did you applied the rotational power?

**Comment by Rodrigo816** [comment]
I tried 3 different methods power apllied via Waterwheel/ steam engine/ and creative motor. and it was simply connecting power to the "optical source"

**Comment by luccaPossamai** [comment]
Just released a new version with some fixes, you could try if the problem persists.

**Comment by luccaPossamai** [comment]
I tested in server side and got the same crash. I fix it, but who knows, maybe there's another reason for your crash
