### ISSUE TITLE
Light is getting blocked by not full blocks

### ISSUE THREAD

**Issue by DaPuffer** [luccaPossamai/optical#3]
![image](https://github.com/luccaPossamai/optical/assets/132820752/f71e97ff-4d6f-44cf-9976-7448d54c0e13)
They probably should go thru slabs and stairs when placed correctly,so you could make less easily detectable laser walls. same with optical sensors

**Comment by luccaPossamai** [comment]
In the next release this issue got fixed. Beams will pass through based on the mod block tag "beams_pass_through" (very descriptive). I think the blocks with this tag can be changed by json files, I'm not really IN this data pack system. But, for now, signs, banners, slabs, carpets, redstone, candles and other cannot block light anymore.
