### ISSUE TITLE
No gamma ray death message

### ISSUE THREAD

**Issue by DaPuffer** [luccaPossamai/optical#5]
![image](https://github.com/luccaPossamai/optical/assets/132820752/133578a1-ee19-4799-a548-9cefb1d190b8)

**Comment by luccaPossamai** [comment]
Fixed in the next version.
Preview:
![image](https://github.com/luccaPossamai/optical/assets/110493821/edcde1f4-e9bb-4fbf-bec5-f4b7fc1ea827)
