### ISSUE TITLE
Beaming the bottom of a splitter crash

### ISSUE THREAD

**Issue by AtobaAzul** [luccaPossamai/optical#7]
If you shine a laser under (and probably above) a Polarizing Beam Splitter, the game crashes.

[latest.log](https://github.com/user-attachments/files/15931232/latest.log)
[crash-2024-06-21_14.55.04-server.txt](https://github.com/user-attachments/files/15931233/crash-2024-06-21_14.55.04-server.txt)

Steps to reproduce:
https://github.com/luccaPossamai/optical/assets/94794129/92eb4e46-3cae-4aeb-a49a-49d3b941dcc2

**Comment by luccaPossamai** [comment]
Yup, I uploaded to curseforge the version before testing. In newer versions this bug would not exist.
