### ISSUE TITLE
Beams not passing through glass panes

### ISSUE THREAD

**Issue by Frosticle** [luccaPossamai/optical#8]
Optical beams aren't passing through glass panes. You probably forgot to add the tag.

Beams also aren't passing through Quark's framed glass and glass panes.

Consider using forge tags, like #forge:glass and #forge:glass_panes.

**Comment by Frosticle** [comment]
I wanted to make a PR for this since it seems like a simple fix, but I couldn't run the mod due to it missing the PolarizingBeamSplitterBlockEntity and PolarizingBeamSplitterRenderer on github.

**Comment by luccaPossamai** [comment]
Yup, the beam condition to pass through transparent blocks(glasses) is hard coded. Thats exists to control the beam color with stained glass. But, maybe I forgot to adding normal glass to this gate. Feel free to make your request, I've just pushed the changes to git.
